package com.minicompiler.service;

import com.minicompiler.domain.entity.AiChatHistory;
import com.minicompiler.domain.repository.AiChatHistoryRepository;
import com.minicompiler.dto.response.AiHistoryResponse;
import com.minicompiler.exception.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Service managing persistence and retrieval of AI chat history entries.
 */
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class AiHistoryService {

    private final AiChatHistoryRepository repository;

    // =========================================================================
    // Public API
    // =========================================================================

    /**
     * Returns the most recent history entries up to {@code limit}.
     *
     * @param  limit maximum number of entries to return
     * @return list of history responses ordered by creation date descending
     */
    public List<AiHistoryResponse> findRecent(int limit) {
        return repository.findAllByOrderByCreatedAtDesc(PageRequest.of(0, limit))
                .getContent().stream()
                .map(this::toResponse)
                .toList();
    }

    /**
     * Persists a new AI chat exchange and returns its response representation.
     *
     * @param userContent      the message submitted by the user
     * @param assistantContent the response generated by the AI
     * @param action           the action type that triggered the exchange
     * @param responseTimeMs   time in milliseconds the AI took to respond
     * @return the saved entry as an {@link AiHistoryResponse}
     */
    @Transactional
    public AiHistoryResponse save(String userContent, String assistantContent,
                                  String action, long responseTimeMs) {
        var entity = AiChatHistory.builder()
                .userContent(userContent)
                .assistantContent(assistantContent)
                .action(action)
                .responseTimeMs(responseTimeMs)
                .build();
        return toResponse(repository.save(entity));
    }

    /**
     * Deletes a single history entry by its ID.
     *
     * @param  id the ID of the entry to delete
     * @throws ResourceNotFoundException if no entry exists with the given ID
     */
    @Transactional
    public void deleteById(Long id) {
        if (!repository.existsById(id)) throw new ResourceNotFoundException("AiHistory", id);
        repository.deleteById(id);
    }

    /** Permanently removes all chat history entries. */
    @Transactional
    public void clearAll() {
        repository.deleteAll();
    }

    // =========================================================================
    // Mapper
    // =========================================================================

    private AiHistoryResponse toResponse(AiChatHistory h) {
        return new AiHistoryResponse(
                h.getId(), h.getUserContent(), h.getAssistantContent(),
                h.getAction(), h.getResponseTimeMs(), h.getCreatedAt());
    }
}