package com.minicompiler.dto.response;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.LocalDateTime;

/**
 * Response body representing a single AI chat history entry.
 * Fields with {@code null} values are excluded from JSON serialization.
 *
 * @param id               unique identifier of the history entry
 * @param userContent      the message or prompt submitted by the user
 * @param assistantContent the response generated by the AI assistant
 * @param action           the action type that triggered this exchange
 * @param responseTimeMs   time in milliseconds the AI took to respond
 * @param createdAt        timestamp when this entry was persisted
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AiHistoryResponse(
        Long          id,
        String        userContent,
        String        assistantContent,
        String        action,
        long          responseTimeMs,
        LocalDateTime createdAt
) {}