package com.minicompiler.compiler.vm;

import com.minicompiler.compiler.codegen.Instruction;
import com.minicompiler.compiler.codegen.OpCode;
import com.minicompiler.exception.CompilerException;

import java.util.*;

/**
 * Stack-based virtual machine responsible for executing bytecode instructions.
 *
 * <p>This VM executes instructions generated by the compiler code generator
 * using a stack-oriented execution model.
 */
public class VirtualMachine {

    // =========================================================================
    // Constants
    // =========================================================================

    private static final int MAX_INSTRUCTIONS = 100_000;
    private static final int MAX_STACK_DEPTH = 1_000;

    private static final String VM_PHASE = "VM";

    private static final String ERR_DIVISION_ZERO = "Division by zero";
    private static final String ERR_MODULO_ZERO = "Modulo by zero";
    private static final String ERR_STACK_OVERFLOW = "Stack overflow";
    private static final String ERR_STACK_UNDERFLOW = "Stack underflow";
    private static final String ERR_EXEC_LIMIT =
            "Execution limit exceeded (possible infinite loop)";

    private static final String ERR_UNDEFINED_VAR = "Undefined variable: ";
    private static final String ERR_UNDEFINED_FUNC = "Undefined function: ";
    private static final String ERR_UNDEFINED_LABEL = "Undefined label: ";
    private static final String ERR_UNKNOWN_OPCODE = "Unknown opcode: ";
    private static final String ERR_CANNOT_NEGATE = "Cannot negate: ";
    private static final String ERR_CANNOT_CONVERT = "Cannot convert to number: ";

    private static final String ERROR_FORMAT = "[%s] L%d: %s";

    // =========================================================================
    // Fields
    // =========================================================================

    private final Deque<Object> stack;
    private final Deque<Frame> callStack;
    private final List<String> output;
    private final Map<String, Integer> labelMap;
    private final Map<String, Integer> functionTable;

    private Map<String, Object> memory;

    /**
     * Stack frame for function calls.
     */
    private record Frame(Map<String, Object> memory, int returnAddress) {}

    // =========================================================================
    // Constructor
    // =========================================================================

    /**
     * Creates a new virtual machine instance.
     *
     * @param functionTable function-name to instruction-index map
     */
    public VirtualMachine(final Map<String, Integer> functionTable) {

        this.stack = new ArrayDeque<>();
        this.callStack = new ArrayDeque<>();
        this.memory = new HashMap<>();
        this.output = new ArrayList<>();
        this.labelMap = new HashMap<>();
        this.functionTable = functionTable;
    }

    // =========================================================================
    // Public API
    // =========================================================================

    /**
     * Executes a list of bytecode instructions.
     *
     * @param instructions instruction list
     * @return execution result
     */
    public ExecutionResult execute(final List<Instruction> instructions) {

        final long start = System.currentTimeMillis();

        buildLabelMap(instructions);

        int ip = 0;
        int executed = 0;

        try {

            while (ip < instructions.size()) {

                if (executed++ > MAX_INSTRUCTIONS) {
                    return buildError(ERR_EXEC_LIMIT, executed, start);
                }

                final var instr = instructions.get(ip);

                ip++;

                switch (instr.opCode()) {

                    case NOP, LABEL -> {
                    }

                    case HALT -> {
                        return buildSuccess(executed, start);
                    }

                    // =========================================================
                    // Stack operations
                    // =========================================================

                    case PUSH -> push(instr.operand());

                    case POP -> pop();

                    case DUP -> push(peek());

                    case SWAP -> {
                        final var a = pop();
                        final var b = pop();

                        push(a);
                        push(b);
                    }

                    // =========================================================
                    // Arithmetic operations
                    // =========================================================

                    case ADD -> {
                        final var b = pop();
                        final var a = pop();

                        push(addValues(a, b));
                    }

                    case SUB -> {
                        final var b = pop();
                        final var a = pop();

                        push(numericOp(a, b, "-"));
                    }

                    case MUL -> {
                        final var b = pop();
                        final var a = pop();

                        push(numericOp(a, b, "*"));
                    }

                    case DIV -> {

                        final var b = pop();
                        final var a = pop();

                        if (toDouble(b) == 0) {
                            throw new CompilerException(
                                    ERR_DIVISION_ZERO,
                                    VM_PHASE,
                                    instr.line(),
                                    0
                            );
                        }

                        push(numericOp(a, b, "/"));
                    }

                    case MOD -> {

                        final var b = pop();
                        final var a = pop();

                        if (toDouble(b) == 0) {
                            throw new CompilerException(
                                    ERR_MODULO_ZERO,
                                    VM_PHASE,
                                    instr.line(),
                                    0
                            );
                        }

                        push((int) (toLong(a) % toLong(b)));
                    }

                    case POW -> {

                        final var b = pop();
                        final var a = pop();

                        push(Math.pow(toDouble(a), toDouble(b)));
                    }

                    case NEG -> push(negateValue(pop()));

                    // =========================================================
                    // Comparison operations
                    // =========================================================

                    case EQ -> {
                        final var b = pop();
                        final var a = pop();

                        push(equalsValues(a, b));
                    }

                    case NEQ -> {
                        final var b = pop();
                        final var a = pop();

                        push(!equalsValues(a, b));
                    }

                    case LT -> {
                        final var b = pop();
                        final var a = pop();

                        push(toDouble(a) < toDouble(b));
                    }

                    case LTE -> {
                        final var b = pop();
                        final var a = pop();

                        push(toDouble(a) <= toDouble(b));
                    }

                    case GT -> {
                        final var b = pop();
                        final var a = pop();

                        push(toDouble(a) > toDouble(b));
                    }

                    case GTE -> {
                        final var b = pop();
                        final var a = pop();

                        push(toDouble(a) >= toDouble(b));
                    }

                    // =========================================================
                    // Boolean operations
                    // =========================================================

                    case AND -> {
                        final var b = pop();
                        final var a = pop();

                        push(toBool(a) && toBool(b));
                    }

                    case OR -> {
                        final var b = pop();
                        final var a = pop();

                        push(toBool(a) || toBool(b));
                    }

                    case NOT -> push(!toBool(pop()));

                    // =========================================================
                    // Memory operations
                    // =========================================================

                    case LOAD ->
                            loadVariable(
                                    (String) instr.operand(),
                                    instr.line()
                            );

                    case STORE ->
                            memory.put((String) instr.operand(), pop());

                    case LOAD_CONST -> push(instr.operand());

                    // =========================================================
                    // Jump operations
                    // =========================================================

                    case JUMP ->
                            ip = resolveLabel(
                                    (String) instr.operand(),
                                    instr.line()
                            );

                    case JUMP_IF_FALSE -> {

                        if (!toBool(pop())) {

                            ip = resolveLabel(
                                    (String) instr.operand(),
                                    instr.line()
                            );
                        }
                    }

                    case JUMP_IF_TRUE -> {

                        if (toBool(pop())) {

                            ip = resolveLabel(
                                    (String) instr.operand(),
                                    instr.line()
                            );
                        }
                    }

                    // =========================================================
                    // Function operations
                    // =========================================================

                    case DEFINE_FUNC -> {
                    }

                    case CALL -> {

                        final var funcName = (String) instr.operand();

                        final var funcAddr = functionTable.get(funcName);

                        if (funcAddr == null) {

                            throw new CompilerException(
                                    ERR_UNDEFINED_FUNC + funcName,
                                    VM_PHASE,
                                    instr.line(),
                                    0
                            );
                        }

                        callStack.push(
                                new Frame(
                                        new HashMap<>(memory),
                                        ip
                                )
                        );

                        memory = new HashMap<>(memory);

                        ip = funcAddr;
                    }

                    case RETURN -> {

                        final var returnValue = pop();

                        final var frame = callStack.pop();

                        memory = frame.memory();

                        ip = frame.returnAddress();

                        push(returnValue);
                    }

                    // =========================================================
                    // IO operations
                    // =========================================================

                    case PRINT -> output.add(formatValue(pop()));

                    case INPUT ->
                            memory.put(
                                    (String) instr.operand(),
                                    "<<input>>"
                            );

                    default -> throw new CompilerException(
                            ERR_UNKNOWN_OPCODE + instr.opCode(),
                            VM_PHASE,
                            instr.line(),
                            0
                    );
                }

                if (stack.size() > MAX_STACK_DEPTH) {

                    throw new CompilerException(
                            ERR_STACK_OVERFLOW,
                            VM_PHASE,
                            instr.line(),
                            0
                    );
                }
            }

        } catch (CompilerException e) {

            return buildError(
                    ERROR_FORMAT.formatted(
                            e.getPhase(),
                            e.getLine(),
                            e.getMessage()
                    ),
                    executed,
                    start
            );
        }

        return buildSuccess(executed, start);
    }

    // =========================================================================
    // Memory helpers
    // =========================================================================

    /**
     * Loads a variable from memory and pushes it onto the stack.
     *
     * @param variableName variable identifier
     * @param line source-code line
     */
    private void loadVariable(
            final String variableName,
            final int line
    ) {

        final Object value = memory.get(variableName);

        if (value == null && !memory.containsKey(variableName)) {

            throw new CompilerException(
                    ERR_UNDEFINED_VAR + variableName,
                    VM_PHASE,
                    line,
                    0
            );
        }

        push(value);
    }

    // =========================================================================
    // Label handling
    // =========================================================================

    private void buildLabelMap(final List<Instruction> instructions) {

        for (int i = 0; i < instructions.size(); i++) {

            final var instr = instructions.get(i);

            if (instr.opCode() == OpCode.LABEL) {

                labelMap.put(
                        String.valueOf(instr.operand()),
                        i
                );
            }
        }
    }

    // =========================================================================
    // Result builders
    // =========================================================================

    private ExecutionResult buildSuccess(
            final int executed,
            final long start
    ) {

        return ExecutionResult.builder()
                .success(true)
                .output(output)
                .finalMemory(new HashMap<>(memory))
                .instructionsExecuted(executed)
                .executionTimeMs(System.currentTimeMillis() - start)
                .build();
    }

    private ExecutionResult buildError(
            final String error,
            final int executed,
            final long start
    ) {

        return ExecutionResult.builder()
                .success(false)
                .output(output)
                .error(error)
                .instructionsExecuted(executed)
                .executionTimeMs(System.currentTimeMillis() - start)
                .build();
    }

    // =========================================================================
    // Stack helpers
    // =========================================================================

    private void push(final Object value) {
        stack.push(value);
    }

    private Object pop() {

        if (stack.isEmpty()) {

            throw new CompilerException(
                    ERR_STACK_UNDERFLOW,
                    VM_PHASE,
                    0,
                    0
            );
        }

        return stack.pop();
    }

    private Object peek() {

        if (stack.isEmpty()) {

            throw new CompilerException(
                    ERR_STACK_UNDERFLOW + " (peek)",
                    VM_PHASE,
                    0,
                    0
            );
        }

        return stack.peek();
    }

    private int resolveLabel(
            final String label,
            final int line
    ) {

        final var addr = labelMap.get(label);

        if (addr == null) {

            throw new CompilerException(
                    ERR_UNDEFINED_LABEL + label,
                    VM_PHASE,
                    line,
                    0
            );
        }

        return addr + 1;
    }

    // =========================================================================
    // Value helpers
    // =========================================================================

    private Object addValues(
            final Object a,
            final Object b
    ) {

        if (a instanceof String || b instanceof String) {
            return formatValue(a) + formatValue(b);
        }

        return numericOp(a, b, "+");
    }

    private Object numericOp(
            final Object a,
            final Object b,
            final String op
    ) {

        final boolean isInt =
                (a instanceof Integer) &&
                        (b instanceof Integer);

        final double da = toDouble(a);
        final double db = toDouble(b);

        final double result = switch (op) {

            case "+" -> da + db;
            case "-" -> da - db;
            case "*" -> da * db;
            case "/" -> da / db;

            default -> throw new IllegalArgumentException(
                    "Unknown op: " + op
            );
        };

        return isInt ? (int) result : result;
    }

    private Object negateValue(final Object value) {

        if (value instanceof Integer i) {
            return -i;
        }

        if (value instanceof Double d) {
            return -d;
        }

        throw new CompilerException(
                ERR_CANNOT_NEGATE + value,
                VM_PHASE,
                0,
                0
        );
    }

    private boolean equalsValues(
            final Object a,
            final Object b
    ) {

        if (a == null && b == null) {
            return true;
        }

        if (a == null || b == null) {
            return false;
        }

        if (a instanceof Number na &&
                b instanceof Number nb) {

            return Double.compare(
                    na.doubleValue(),
                    nb.doubleValue()
            ) == 0;
        }

        return a.equals(b);
    }

    private double toDouble(final Object value) {

        if (value instanceof Integer i) {
            return i.doubleValue();
        }

        if (value instanceof Double d) {
            return d;
        }

        if (value instanceof Float f) {
            return f.doubleValue();
        }

        if (value instanceof Long l) {
            return l.doubleValue();
        }

        if (value instanceof Boolean b) {
            return b ? 1.0 : 0.0;
        }

        throw new CompilerException(
                ERR_CANNOT_CONVERT + value,
                VM_PHASE,
                0,
                0
        );
    }

    private long toLong(final Object value) {
        return (long) toDouble(value);
    }

    private boolean toBool(final Object value) {

        if (value == null) {
            return false;
        }

        if (value instanceof Boolean b) {
            return b;
        }

        if (value instanceof Integer i) {
            return i != 0;
        }

        if (value instanceof Double d) {
            return d != 0.0;
        }

        if (value instanceof String s) {
            return !s.isEmpty();
        }

        return true;
    }

    private String formatValue(final Object value) {

        if (value == null) {
            return "null";
        }

        if (value instanceof Double d) {

            if (
                    d == Math.floor(d) &&
                            !Double.isInfinite(d)
            ) {
                return String.valueOf(d.intValue());
            }

            return String.valueOf(d);
        }

        return String.valueOf(value);
    }
}