# Server
server.port=${PORT:8080}

# App
spring.application.name=minicompiler-backend

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# Gemini AI
app.gemini.api-key=${AIzaSyBkUpD3yw7y9gjfUptP345os7CGfyFsp2I}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.com.minicompiler=DEBUG
logging.level.org.springframework.web=INFO