package com.minicompiler.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request body for compilation endpoints.
 *
 * @param sourceCode   the source code to compile; must not be blank and max 10 000 chars
 * @param optimize     whether to apply the optimizer pass before execution
 * @param showTokens   whether to include the token list in the response
 * @param showAst      whether to include the AST representation in the response
 * @param showBytecode whether to include the generated bytecode in the response
 */
public record CompileRequest(
        @NotBlank(message = "Source code cannot be blank")
        @Size(max = 10_000, message = "Source code too large (max 10000 chars)")
        String sourceCode,

        boolean optimize,
        boolean showTokens,
        boolean showAst,
        boolean showBytecode
) {}