package com.minicompiler.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single AI chat exchange stored in the
 * {@code ai_chat_history} table.
 */
@Entity
@Table(name = "ai_chat_history")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class AiChatHistory {

    /** Auto-generated primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The message or prompt submitted by the user. */
    @Column(columnDefinition = "TEXT")
    private String userContent;

    /** The response generated by the AI assistant. */
    @Column(columnDefinition = "TEXT", nullable = false)
    private String assistantContent;

    /** The action type that triggered this exchange (e.g. {@code EXPLAIN}). */
    @Column(length = 50)
    private String action;

    /** Time in milliseconds the AI took to produce the response. */
    @Column(nullable = false)
    private long responseTimeMs;

    /** Timestamp set automatically at insert time, never updated. */
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
}