package com.minicompiler.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single compilation attempt stored in the
 * {@code compilation_records} table.
 */
@Entity
@Table(name = "compilation_records")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class CompilationRecord {

    /** Auto-generated primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The session this record belongs to; loaded lazily. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "session_id")
    private CompilationSession session;

    /** Raw source code submitted for compilation. */
    @Column(columnDefinition = "TEXT", nullable = false)
    private String sourceCode;

    /** Standard output produced during execution; {@code null} on failure. */
    @Column(columnDefinition = "TEXT")
    private String output;

    /** String representation of the generated bytecode instructions. */
    @Column(columnDefinition = "TEXT")
    private String bytecode;

    /** {@code true} if compilation and execution completed without errors. */
    @Column(nullable = false)
    private boolean success;

    /** Human-readable error message; {@code null} when {@link #success} is {@code true}. */
    @Column(length = 500)
    private String errorMessage;

    /** Total time in milliseconds from compilation start to execution end. */
    @Column(nullable = false)
    private long compilationTimeMs;

    /** Number of bytecode instructions dispatched during execution. */
    @Column(nullable = false)
    private int instructionsExecuted;

    /** {@code true} if the optimizer pass was applied before execution. */
    @Column(nullable = false)
    private boolean optimized;

    /** Timestamp set automatically at insert time, never updated. */
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
}